// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT1oBHsrxhgrmAX_8Tmz1Dl-p4t9we7ac',
    appId: '1:466305741476:web:6e57a7f0faef059809ec31',
    messagingSenderId: '466305741476',
    projectId: 'coach-assistant-245bc',
    authDomain: 'coach-assistant-245bc.firebaseapp.com',
    storageBucket: 'coach-assistant-245bc.appspot.com',
    measurementId: 'G-0R05XSF6DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBld9sw4w494PIWHCNVPZ5QREHK-hMi1wE',
    appId: '1:466305741476:android:e45ae0fa68461cfc09ec31',
    messagingSenderId: '466305741476',
    projectId: 'coach-assistant-245bc',
    storageBucket: 'coach-assistant-245bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaHBelfKVkTQDg5xCUTFrGZcJ5G3EzX1g',
    appId: '1:466305741476:ios:0f0e9e05b7cc66d009ec31',
    messagingSenderId: '466305741476',
    projectId: 'coach-assistant-245bc',
    storageBucket: 'coach-assistant-245bc.appspot.com',
    iosBundleId: 'com.example.coachAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaHBelfKVkTQDg5xCUTFrGZcJ5G3EzX1g',
    appId: '1:466305741476:ios:0f0e9e05b7cc66d009ec31',
    messagingSenderId: '466305741476',
    projectId: 'coach-assistant-245bc',
    storageBucket: 'coach-assistant-245bc.appspot.com',
    iosBundleId: 'com.example.coachAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT1oBHsrxhgrmAX_8Tmz1Dl-p4t9we7ac',
    appId: '1:466305741476:web:aff272dad06008ed09ec31',
    messagingSenderId: '466305741476',
    projectId: 'coach-assistant-245bc',
    authDomain: 'coach-assistant-245bc.firebaseapp.com',
    storageBucket: 'coach-assistant-245bc.appspot.com',
    measurementId: 'G-TY0SGYYQXL',
  );

}